[package]
name = "p3-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = "0.1"
tokio = { version = "1.37", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
dashmap = "5.5"
solana-sdk = "1.18"
cadence-macros = "0.5"

